# Generated by Django 3.1.3 on 2020-11-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=50)),
                ('p_email', models.EmailField(max_length=254, unique=True)),
                ('d_email', models.EmailField(max_length=254, unique=True)),
                ('appoint_date', models.DateField()),
                ('appoint_time', models.TimeField()),
                ('symptoms', models.CharField(max_length=120)),
                ('prescription', models.CharField(max_length=300)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=15)),
                ('bloodGroup', models.CharField(max_length=4)),
                ('DOB', models.DateField()),
                ('specialization', models.CharField(max_length=40)),
            ],
        ),
    ]
